export declare const ITEMS_DAT_URL = "https://raw.githubusercontent.com/StileDevs/itemsdat-archive/refs/heads/main";
export declare const ITEMS_DAT_FETCH_URL = "https://raw.githubusercontent.com/StileDevs/itemsdat-archive/refs/heads/main/latest.json";
export declare enum PacketTypes {
    HELLO = 1,
    STR = 2,
    ACTION = 3,
    TANK = 4
}
export declare const WORLD_SIZE: {
    WIDTH: number;
    HEIGHT: number;
};
export declare const STRING_CIPHER_KEY = "PBG892FXX982ABC*";
export declare const Y_START_DIRT = 24;
export declare const Y_LAVA_START = 50;
export declare const Y_END_DIRT = 55;
export declare const ROLE: {
    DEVELOPER: string;
    BASIC: string;
    SUPPORTER: string;
};
export declare enum ClothTypes {
    HAIR = 0,
    SHIRT = 1,
    PANTS = 2,
    FEET = 3,
    FACE = 4,
    HAND = 5,
    BACK = 6,
    MASK = 7,
    NECKLACE = 8,
    ANCES = 9
}
export declare const CLOTH_MAP: {
    [key in ClothTypes]: string;
};
export declare enum TankTypes {
    STATE = 0,
    CALL_FUNCTION = 1,
    UPDATE_STATUS = 2,
    TILE_CHANGE_REQUEST = 3,
    SEND_MAP_DATA = 4,
    SEND_TILE_UPDATE_DATA = 5,
    SEND_TILE_UPDATE_DATA_MULTIPLE = 6,
    TILE_ACTIVATE_REQUEST = 7,
    TILE_APPLY_DAMAGE = 8,
    SEND_INVENTORY_STATE = 9,
    ITEM_ACTIVATE_REQUEST = 10,
    ITEM_ACTIVATE_OBJECT_REQUEST = 11,
    SEND_TILE_TREE_STATE = 12,
    MODIFY_ITEM_INVENTORY = 13,
    ITEM_CHANGE_OBJECT = 14,
    SEND_LOCK = 15,
    SEND_ITEM_DATABASE_DATA = 16,
    SEND_PARTICLE_EFFECT = 17,
    SET_ICON_STATE = 18,
    ITEM_EFFECT = 19,
    SET_CHARACTER_STATE = 20,
    PING_REPLY = 21,
    PING_REQUEST = 22,
    GOT_PUNCHED = 23,
    APP_CHECK_RESPONSE = 24,
    APP_INTEGRITY_FAIL = 25,
    DISCONNECT = 26,
    BATTLE_JOIN = 27,
    BATTLE_EVEN = 28,
    USE_DOOR = 29,
    SEND_PARENTAL = 30,
    GONE_FISHIN = 31,
    STEAM = 32,
    PET_BATTLE = 33,
    NPC = 34,
    SPECIAL = 35,
    SEND_PARTICLE_EFFECT_V2 = 36,
    ACTIVE_ARROW_TO_ITEM = 37,
    SELECT_TILE_INDEX = 38,
    SEND_PLAYER_TRIBUTE_DATA = 39
}
export declare enum TileFlags {
    TILEEXTRA = 1,
    LOCKED = 2,
    SEED = 16,
    TREE = 25,
    FLIPPED = 32,
    ROTATED_LEFT = 48,
    OPEN = 64,
    PUBLIC = 128,
    SILENCED = 512,
    WATER = 1024,
    FIRE = 4096,
    RED = 8192,
    BLUE = 32768,
    GREEN = 16384,
    YELLOW = 24576,
    PURPLE = 40960
}
export declare enum TileExtraTypes {
    NONE = 0,
    DOOR = 1,
    MAIN_DOOR = 1,
    SIGN = 2,
    LOCK = 3,
    SEED = 4,
    MAILBOX = 6,
    BULLETIN = 7,
    DICE = 8,
    PROVIDER = 9,
    ACHIEVEMENT = 10,
    HEART_MONITOR = 11,
    DONATION_BLOCK = 12,
    TOYBOX = 13,
    MANNEQUIN = 14,
    MAGIC_EGG = 15,
    GAME_RESOURCES = 16,
    GAME_GENERATOR = 17,
    XENONITE = 18,
    DESSUP = 19,
    CRYSTAL = 20,
    BURGLAR = 21,
    SPOTLIGHT = 22,
    DISPLAY_BLOCK = 23,
    VENDING_MACHINE = 24,
    FISHTANK = 25,
    SOLAR = 26,
    FORGE = 27,
    GIVING_TREE = 28,
    GIVING_TREE_STUMP = 29,
    STEAM_ORGAN = 30,
    TAMAGOTCHI = 31,
    SWING = 32,
    FLAG = 33,
    LOBSTER_TRAP = 34,
    ART_CANVAS = 35,
    BATTLE_CAGE = 36,
    PET_TRAINER = 37,
    STEAM_ENGINE = 38,
    LOCKBOT = 39,
    WEATHER_SPECIAL = 40,
    SPIRIT_STORAGE = 41,
    UNKNOWN_1 = 42,
    DISPLAY_SHELF = 43,
    VIP_ENTRANCE = 44,
    CHALLENGE_TIMER = 45,
    CHALLENGE_FLAG = 46,
    FISH_MOUNT = 47,
    PORTRAIT = 48,
    WEATHER_SPECIAL2 = 49,
    FOSSIL_PREP = 50,
    DNA_MACHINE = 51,
    MAGPLANT = 62,
    GROWSCAN = 66,
    TESSERACT_MANIPULATOR = 69,
    GAIA_HEART = 70,
    TECHNO_ORGANIC_ENGINE = 71,
    KRANKEN_GALACTIC = 80,
    WEATHER_INFINITY = 77
}
export declare enum TileCollisionTypes {
    NONE = 0,
    NORMAL = 1,
    JUMP_THROUGH = 2,
    GATEWAY = 3,
    IF_OFF = 4,
    ONE_WAY = 5,
    VIP = 6,
    WATERFALL = 7,
    ADVENTURE = 8,
    IF_ON = 9,
    TEAM_ENTRANCE = 10,
    GUILD = 11,
    CLOUD = 12,
    FRIEND_ENTRANCE = 13
}
export declare enum ActionTypes {
    FIST = 0,
    WRENCH = 1,
    DOOR = 2,
    LOCK = 3,
    GEMS = 4,
    TREASURE = 5,
    DEADLY_BLOCK = 6,
    TRAMPOLINE = 7,
    CONSUMABLE = 8,
    GATEWAY = 9,
    SIGN = 10,
    SFX_WITH_EXTRA_FRAME = 11,
    BOOMBOX = 12,
    MAIN_DOOR = 13,
    PLATFORM = 14,
    BEDROCK = 15,
    LAVA = 16,
    FOREGROUND = 17,
    BACKGROUND = 18,
    SEED = 19,
    CLOTHES = 20,
    FOREGROUND_WITH_EXTRA_FRAME = 21,
    BACKGD_SFX_EXTRA_FRAME = 22,
    BACK_BOOMBOX = 23,
    BOUNCY = 24,
    POINTY = 25,
    PORTAL = 26,
    CHECKPOINT = 27,
    SHEET_MUSIC = 28,
    ICE = 29,
    SWITCHEROO = 31,
    CHEST = 32,
    MAILBOX = 33,
    BULLETIN = 34,
    PINATA = 35,
    DICE = 36,
    CHEMICAL = 37,
    PROVIDER = 38,
    LAB = 39,
    ACHIEVEMENT = 40,
    WEATHER_MACHINE = 41,
    SCORE_BOARD = 42,
    SUNGATE = 43,
    PROFILE = 44,
    DEADLY_IF_ON = 45,
    HEART_MONITOR = 46,
    DONATION_BOX = 47,
    TOYBOX = 48,
    MANNEQUIN = 49,
    SECURITY_CAMERA = 50,
    MAGIC_EGG = 51,
    GAME_RESOURCES = 52,
    GAME_GENERATOR = 53,
    XENONITE = 54,
    DRESSUP = 55,
    CRYSTAL = 56,
    BURGLAR = 57,
    COMPACTOR = 58,
    SPOTLIGHT = 59,
    WIND = 60,
    DISPLAY_BLOCK = 61,
    VENDING_MACHINE = 62,
    FISHTANK = 63,
    PETFISH = 64,
    SOLAR = 65,
    FORGE = 66,
    GIVING_TREE = 67,
    GIVING_TREE_STUMP = 68,
    STEAMPUNK = 69,
    STEAM_LAVA_IF_ON = 70,
    STEAM_ORGAN = 71,
    TAMAGOTCHI = 72,
    SWING = 73,
    FLAG = 74,
    LOBSTER_TRAP = 75,
    ART_CANVAS = 76,
    BATTLE_CAGE = 77,
    PET_TRAINER = 78,
    STEAM_ENGINE = 79,
    LOCKBOT = 80,
    WEATHER_SPECIAL = 81,
    SPIRIT_STORAGE = 82,
    DISPLAY_SHELF = 83,
    VIP_ENTRANCE = 84,
    CHALLENGE_TIMER = 85,
    CHALLENGE_FLAG = 86,
    FISH_MOUNT = 87,
    PORTRAIT = 88,
    WEATHER_SPECIAL2 = 89,
    FOSSIL = 90,
    FOSSIL_PREP = 91,
    DNA_MACHINE = 92,
    BLASTER = 93,
    VALHOWLA = 94,
    CHEMSYNTH = 95,
    CHEMTANK = 96,
    STORAGE = 97,
    OVEN = 98,
    SUPER_MUSIC = 99,
    GEIGER_CHARGER = 100,
    ADVENTURE_RESET = 101,
    TOMB_ROBBER = 102,
    FACTION = 103,
    RED_FACTION = 104,
    GREEN_FACTION = 105,
    BLUE_FACTION = 106,
    ANCES = 107,
    FISHGOTCHI_TANK = 109,
    FISHING_BLOCK = 110,
    ITEM_SUCKER = 111,
    ITEM_PLANTER = 112,
    ROBOT = 113,
    COMMAND = 114,
    TICKET = 115,
    STATS_BLOCK = 116,
    FIELD_NODE = 117,
    OUIJA_BOARD = 118,
    ARCHITECT_MACHINE = 119,
    STARSHIP = 120,
    AUTODELETE = 121,
    GREEN_FOUNTAIN = 122,
    AUTO_ACTION_BREAK = 123,
    AUTO_ACTION_HARVEST = 124,
    AUTO_ACTION_HARVEST_SUCK = 125,
    LIGHTNING_IF_ON = 126,
    PHASED_BLOCK = 127,
    MUD = 128,
    ROOT_CUTTING = 129,
    PASSWORD_STORAGE = 130,
    PHASED_BLOCK_2 = 131,
    BOMB = 132,
    WEATHER_INFINITY = 134,
    SLIME = 135,
    UNK1 = 136,
    COMPLETIONIST = 137,
    UNK3 = 138,
    FEEDING_BLOCK = 140,
    KRANKENS_BLOCK = 141,
    FRIENDS_ENTRANCE = 142
}
export declare const LOCKS: {
    id: number;
    maxTiles: number;
}[];
export declare const TileIgnore: {
    blockIDsToIgnoreByLock: number[];
    blockActionTypesToIgnore: ActionTypes[];
};
export declare enum BlockFlags {
    MULTI_FACING = 1,
    WRENCHABLE = 2,
    SEEDLESS = 4,// This item never drops any seeds.
    PERMANENT = 8,// This item is permanent.
    DROPLESS = 16,// DROPLESS
    NO_SELF = 32,// This item can't be used on yourself.
    NO_SHADOW = 64,// This item has no shadow.
    WORLD_LOCKED = 128,// This item can only be used in World-Locked worlds.
    BETA = 256,// This item is a beta item.
    AUTO_PICKUP = 512,// This item can't be destroyed - smashing it will return it to your backpack if you have room!
    MOD = 1024,// This item is a mod item.
    RANDOM_GROW = 2048,// A tree of this type can bear surprising fruit!
    PUBLIC = 4096,// This item is PUBLIC: Even if it's locked, anyone can smash it.
    FOREGROUND = 8192,// This item is a foreground item.
    HOLIDAY = 16384,// This item can only be created during WinterFest!
    UNTRADEABLE = 32768
}
export declare enum NameStyles {
    MAX_LEVEL = "maxLevel",
    DOCTOR = "doctor",
    MENTOR = "3",
    GROW4GOOD = "grow4good",
    THANKSGIVING = "thanksgiving",
    YOUTUBE = "youtube",
    TIKTOK = "tiktok",
    MASTER = "master",
    DONOR = "donor",
    EUPHORIA = "euphoria",
    SHOW_GUILD = "showGuild",
    LEGENDARY = " of Legend``",
    DEVELOPER = "`b",
    MOD = "`5",
    OWNER = "`2",
    ACCESS = "`^",
    GAME = "`a"
}
export declare enum CharacterState {
    WALK_IN_BLOCKS = 1,
    DOUBLE_JUMP = 2,
    IS_INVISIBLE = 4,
    NO_HANDS = 8,
    NO_EYES = 16,
    NO_BODY = 32,
    DEVIL_HORNS = 64,
    GOLDEN_HALO = 128,
    IS_FROZEN = 2048,
    IS_CURSED = 4096,
    IS_DUCTAPED = 8192,
    HAVE_CIGAR = 16384,
    IS_SHINING = 32768,
    IS_ZOMBIE = 65536,
    IS_HIT_BY_LAVA = 131072,
    HAVE_HAUNTED_SHADOWS = 262144,
    HAVE_GEIGER_RADIATION = 524288,
    HAVE_REFLECTOR = 1048576,
    IS_EGGED = 2097152,
    HAVE_PINEAPPLE_FLOAT = 4194304,
    HAVE_FLYING_PINEAPPLE = 8388608,
    HAVE_SUPER_SUPPORTER_NAME = 16777216,
    HAVE_SUPER_PINEAPPLE = 33554432
}
export declare enum ModsEffects {
    HARVESTER = 1,
    PUNCH_DAMAGE = 2
}
export declare enum StateFlags {
    NONE = 0,
    UNK = 2,
    RESET_VISUAL_STATE = 4,
    EXTENDED = 8,
    ROTATE_LEFT = 16,
    ON_SOLID = 32,
    ON_FIRE_DAMAGE = 64,
    ON_JUMP = 128,
    ON_KILLED = 256,
    ON_PUNCHED = 512,
    ON_PLACED = 1024,
    ON_TILE_ACTION = 2048,
    ON_GOT_PUNCHED = 4096,
    ON_RESPAWNED = 8192,
    ON_COLLECT_OBJECT = 16384,
    ON_TRAMPOLINE = 32768,
    ON_DAMAGE = 65536,
    ON_SLIDE = 131072,
    ON_WALL_HANG = 2097152,
    ON_ACID_DAMAGE = 67108864
}
export declare const weatherIdMap: Record<number, number>;
